export const POPUPS = {
  EXERCISE_MEMORIZATION_SELECTED_SUCCESS: 'EXERCISE_MEMORIZATION_SELECTED_SUCCESS',
  EXERCISE_MEMORIZATION_SELECTED_FAILED: 'EXERCISE_MEMORIZATION_SELECTED_FAILED',
  EXERCISE_MEMORIZATION_FINISH_ROUND: 'EXERCISE_MEMORIZATION_FINISH_ROUND',
  EXERCISE_MEMORIZATION_FINISH_MODULE: 'EXERCISE_MEMORIZATION_FINISH_MODULE',
  REMINDER_SELECT_LANGUAGE: 'REMINDER_SELECT_LANGUAGE',
  SELECTING_LANGUAGE: 'SELECTING_LANGUAGE',
}

export type PopupName = keyof typeof POPUPS
