export const POPUPS = {
  EXERCISE_MEMORIZATION_SELECTED_SUCCESS: 'EXERCISE_MEMORIZATION_SELECTED_SUCCESS',
  EXERCISE_MEMORIZATION_SELECTED_FAILED: 'EXERCISE_MEMORIZATION_SELECTED_FAILED',
  EXERCISE_MEMORIZATION_FINISH_ROUND: 'EXERCISE_MEMORIZATION_FINISH_ROUND',
}

export type PopupName = keyof typeof POPUPS
