export const ACTIVE_TERM_FORWARD = 'ACTIVE_TERM_FORWARD'
export const ROUND_FORWARD = 'ROUND_FORWARD'
export const ADD_LEANED_TERM = 'ADD_LEANED_TERM'
export const ADD_LEANED_TERM_ROUND = 'ADD_LEANED_TERM_ROUND'
export const UPDATE_TERMS_ROUND = 'UPDATE_TERMS_ROUND'
export const END_MEMORIZATION_MODE = 'END_MEMORIZATION_MODE'
export const UPDATE_MEMORIZATION = 'UPDATE_MEMORIZATION'

export const SUBMIT_LEARNED = 'exercises/SUBMIT_LEARNED'
