name: Deploy-dev

# Override previous workflow run (skip all pending runs within one branch)
concurrency:
  group: "dev-build-${{ github.head_ref }}"
  cancel-in-progress: true

env:
  CI: false

on:
  pull_request:
    types: [ opened, reopened, synchronize, labeled ]

jobs:
  init:
    runs-on: ubuntu-20.04
    # Trigger when:
    # PR develop->main/master
    # Any PR with 'deploy' label'
    #
    # Do not trigger when:
    # PR main/master->whatever
    if: (github.head_ref == 'develop' && (github.base_ref == 'main' || github.base_ref == 'master')) || contains(github.event.pull_request.labels.*.name, 'deploy')
    steps:
      - uses: actions/checkout@v3
  build:
    runs-on: ubuntu-20.04
    needs: [ init ]
    strategy:
      matrix:
        node-version: [ 18.x ]
    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
      - name: install modules
        run: npm install
      - name: build project
        run: npm run build
      - name: run linter
        run: npm run lint
      - name: run test
        run: npm run test
